name: "Podcast Generator"
author: " Awais "
description: "Generate a feed for a podcast"

runs:
   using: "docker"
   image: "Dockerfile"
branding:
   icon: "git-branch"
   color: "red"
input:
   email:
     description: The committer's email address
     required: true
     
   name:
     description: The committer's name
     required: true
     
                